[[main]]
none = "none"

[[main]]
name = "Posts"
pre = "pencil"
pageRef = "posts"
identifier = "Dx0UjMdkXl"
weight = 9_999

[[main]]
name = "Catagories"
pre = "tag"
pageRef = "tags"
identifier = "YjChmyay3k"
weight = 9_999

[[main]]
pre = "github"
url = "https://github.com/TheAhumMaitra/HauntedSchool"
identifier = "3IXNLn8A9g"
weight = 9_999

[[footer]]
none = "none"
